### ISSUE TITLE
map find error

### ISSUE THREAD

**Issue by xiaostang** [GENIVI/vsomeip#172] opened 2020-11-09 08:07 UTC
### j  is map.end and then use j->second, may cause question
![image](https://user-images.githubusercontent.com/32772277/98515043-68e94b80-22a5-11eb-9657-24df50e62e75.png)

**Comment by lutzbichler** [comment] 2020-11-09 10:32
This is a duplicate of #164

**Closed** 2020-11-09 10:31 UTC
